Deltarune.asl, README.md
Ok
(auto end splits may not be 100% accurate so be weary of that but atleast they work the majority of the time :D)
=> Added Ch1 Auto end, Ch2 Auto start and end, Ch1->2 IGT pause, all for 1.08-1.10 and 1.15

Deltarune.asl
basically if you hover over "No" but dont actually press it and then go to press "Yes" it wouldn't split
=> fixed sp enter+exit jevil room + demo ch1 end not working in specific cases

Deltarune.asl
=> Workaround for using the right fight pointer-1.15

Deltarune.asl
=> Fixed ch1 end triggering without interacting with the bed + changed a couple pointers

Deltarune.asl
Apparently they have the same module memory size shavyYipe
=> Changed v1.15 state{} to v1.13 - v1.15 and change the way how Ch2 end

Deltarune.asl, README.md
=> Added demo key item splits

Deltarune.asl
ty ashmichda for tellin me this
=> Timer pauses now work with the split option off

.github/ISSUE_TEMPLATE/bug_report.md
- Reduce refresh rate to match Deltarune framerate (Lower CPU usage and more accurate trigger)
=> Release 2.0.1

Deltarune.asl
Exit K.Round 2 and Exit Pre-King Room
=> Added different card castle splits

Deltarune.asl
Timer start broke 
now it's not broke :D :D
=> Attempts fix for 1.10

Deltarune.asl
i forgot to add a check, because of that the autosplitter cant split lol!!!!!!
=> Actually fixed 1.10

Deltarune.asl
=> Release 2.1.1a

Deltarune.asl
Caused by using tempVar that is shared for many things
=> Fix false reset trigger in ch1 prison

Deltarune.asl
- Ch1_Jevil_LeaveRoom
- Ch2_Berdly_EndFight (Default)
- Ch2_SGBerdly_LeaveRoom
- Ch2_Berdly_Leave (rename from Ch2_BerdlyLeave)
- Ch2_Berdly_Leave (Not default anymore)
=> Release 2.2.0

Deltarune.asl, README.md, cspell.json
- Renamed:
* Trash Zone Warp -> Warp from Cyber Fields to Trash Zone
* Mansion Warp -> Warp from Cyber Fields to Mansion
- Added:
* Obtain Egg (Ch1&2)
* Warp from Castle to Fields
* Warp from Fields to Bake Sale
* Warp from Bake Sale to Castle (Ch1)
* Warp from Trash Zone to Cyber Fields
* Warp from Trash Zone to Mansion
* Warp from Mansion to Cyber Fields
* Warp from Mansion to Trash Zone (Ch2)
=> Multiple changes

Deltarune.asl
- Optimize splitting process to make the file lighter and easier to maintain with special conditions like text
- Fix a bug making the autosplitter not reseting splits if the game is close
=> Optimization splitting condition

Deltarune.asl
- Fixed 1.09 OST% end split
- Changed how key items are handled (fix egg split breaking with door overflow + it works on SURVEY_PROGRAM)
- Enter Dark World also works with bed skip
=> Release 2.7.3 - diverses changes

Deltarune.asl
=> Add a setting to unpause when loading a save file

Deltarune.asl
Apparently you're allowed to do that in all items
also ac_continue is useless
=> Add a setting to unpause on new file + remove AC_Continue

Deltarune.asl
Apparently you're allowed to do that in all items
also ac_continue is useless
=> Release 3.6.1 - Remove AC_continue & Add unpause on new file
